### PR TITLE
fix: macos nightly build filename since #28000

### LINKED ISSUE #30: Bug: failed to download Neovim nightly for macOS
Hi,

There's an error when install Neovim nightly for macOS:

image

It seems `nvim-macos.tar.gz` is been renamed to `nvim-macos-x86_64.tar.gz` and `nvim-macos-arm64.tar.gz`:

image

### PR DESCRIPTION
**Pull request by linrongbin16**
Fix #30 .

This PR fixes the nightly nvim asset filename for macOS, since https://github.com/neovim/neovim/pull/28000, Neovim nightly build on macOS is renamed from 'nvim-macos.tar.gz' to 'nvim-macos-arm64.tar.gz' and 'nvim-macos-x86_64.tar.gz'.

But seems I cannot test this PR with my forked repo: https://github.com/linrongbin16/action-setup-vim/tree/fix-macos-nightly, I'm blocked for now, will try to test it.

----------------

Update: this PR is tested here: https://github.com/linrongbin16/action-setup-vim/pull/1

### CODE REVIEW

**Comment by rhysd** [comment]
Thank you. I'll take a look at this tonight.

File: src/neovim.ts [hunk 1]
```diff
@@ -46,6 +56,18 @@ export function assetDirName(version: string, os: Os): string {
             if (v !== null && (v.minor < 7 || (v.minor === 7 && v.patch < 1))) {
                 return 'nvim-osx64';
             }
+            // Until v0.9.5 release, 'nvim-macos' was the asset directory name on macOS. However it was changed to 'nvim-macos-arm64'
+            // and 'nvim-macos-x86_64' from v0.10.0: https://github.com/neovim/neovim/pull/28000
+            if (version === 'nightly') {
```
Comment (linrongbin16) [inline src/neovim.ts:61]: After Neovim released the 0.10.0, this `version` will also need to detect `< 0.10.0`, similar to the detection for `0.7.1`.

Comment (rhysd) [reply src/neovim.ts:61]: Is the next version of Neovim fixed to 0.10.0? Or can it be 0.9.6?

Comment (linrongbin16) [reply src/neovim.ts:61]: not sure, I think I had something, Neovim team says 0.10.0 will release in April 2024.

But, I am not sure.

Comment (linrongbin16) [reply src/neovim.ts:61]: Neovim usually create a milestone for a version: https://github.com/neovim/neovim/milestones. (this is highly possible truth because I had followed this issue list for over 2 years).

There's no 0.9.6 in these milestones, so I believe there will be no 0.9.6.

Comment (rhysd) [reply src/neovim.ts:61]: OK, thank you for the information. I'll add the version check when the next version is fixed.

**Review by rhysd — APPROVED** [review]

**Comment by rhysd** [comment]
Shipped v1.3.2: https://github.com/rhysd/action-setup-vim/releases/tag/v1.3.2
